#define BASE_FRAME_LENGTH 0.01f

#define START_COUNTDOWN_SECONDS 5.0f

#define PADDLE_ACCELERATION 2.5f
#define PADDLE_MAX_SPEED 1.5f
#define PADDLE_FRICTION 1.0f

#define PADDLE_X 0.9f
#define PADDLE_WIDTH 0.025f
#define PADDLE_HEIGHT 0.1f
#define BALL_WIDTH 0.025f

#define PADDLE_HALF_WIDTH PADDLE_WIDTH / 2.0f
#define PADDLE_HALF_HEIGHT PADDLE_HEIGHT / 2.0f
#define BALL_HALF_WIDTH BALL_WIDTH / 2.0f
